apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: votehub-legacy-redirect
  namespace: votehub
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/permanent-redirect: https://votehub.me$request_uri
spec:
  ingressClassName: nginx
  rules:
    - host: votehub.zapto.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port:
                  number: 8080
